namespace FermixAPI.Hints.Core.Models.HintContent
{
    using System;
    using FermixAPI.Hints.Core.Models.Arguments;
    using FermixAPI.Hints.Core.Utilities.Tools;

    /// <summary>
    /// Represents hint content that is automatically generated by a user-supplied callback on a periodic schedule.
    /// </summary>
    public class AutoContent : AbstractHintContent
    {
        private DateTime nextUpdateTime;
        private TimeSpan defaultUpdateInterval;

        private string? text;

        private TextUpdateHandler? autoText;

        /// <summary>
        /// Initializes a new instance of the <see cref="AutoContent"/> class.
        /// </summary>
        /// <param name="autoText">The callback invoked to generate the hint text on each update cycle.</param>
        /// <param name="defaultUpdateInterval">The default interval in seconds between updates. Use a negative value to default to 0.1 seconds.</param>
        public AutoContent(TextUpdateHandler? autoText, float defaultUpdateInterval = -1)
        {
            this.autoText = autoText;
            if (defaultUpdateInterval >= 0)
                this.defaultUpdateInterval = TimeSpan.FromSeconds(defaultUpdateInterval);
            else
                this.defaultUpdateInterval = TimeSpan.FromSeconds(0.1);
        }

        /// <summary>
        /// Represents a method that returns the updated hint text given the current update arguments.
        /// </summary>
        /// <param name="ev">The arguments providing context for the text update, including the owning hint and timing information.</param>
        /// <returns>The content of the hint.</returns>
        public delegate string TextUpdateHandler(AutoContentUpdateArg ev);

        /// <summary>
        /// Gets or sets the callback used to generate hint text. Setting this property resets the update timer.
        /// </summary>
        public TextUpdateHandler? AutoText
        {
            get => autoText;
            set
            {
                autoText = value;
                nextUpdateTime = DateTime.MinValue;// Reset Update Time
            }
        }

        /// <summary>
        /// Returns the most recently generated text for this content.
        /// </summary>
        /// <returns>The last generated text string, or <see langword="null"/> if no update has occurred yet.</returns>
        public override string? GetText() => text;

        /// <summary>
        /// Invokes the <see cref="AutoText"/> callback if the scheduled update interval has elapsed,
        /// and raises <see cref="AbstractHintContent.ContentUpdated"/> if the text has changed.
        /// </summary>
        /// <param name="ev">The arguments supplying context for the update.</param>
        public override void TryUpdate(ContentUpdateArg ev)
        {
            if (nextUpdateTime > DateTime.Now)
                return;

            AutoContentUpdateArg autoContentUpdateArg = new(ev.Hint, ev.PlayerDisplay, defaultUpdateInterval);
            string? newText;

            try
            {
                newText = autoText?.Invoke(autoContentUpdateArg);
            }
            catch (Exception ex)
            {
                newText = string.Empty;
                Logger.Instance.Error(ex);
            }

            if (text != newText)
            {
                text = newText;
                OnUpdated();
            }

            nextUpdateTime = DateTime.Now.Add(autoContentUpdateArg.NextUpdateDelay);
            defaultUpdateInterval = autoContentUpdateArg.DefaultUpdateDelay;
        }
    }
}
